### ISSUE TITLE
useKeybind import 

### ISSUE THREAD

**Issue by rockerBOO** [mimshins/utilityjs#2]
useKeybind package on npm is importing

```javascript
var useKeybind_1 = require("./useKeybind");
    Cannot find module './useKeybind' from '../node_modules/@utilityjs/use-
keybind/index.js'
```
but the file is `./useKeyBind`. Changing this fixes it. But looking at the repo it's not using this casing.

```
➜ ls node_modules/@utilityjs/use-keybind/
esm  index.d.ts  index.js  package.json  README.md  useKeyBind.d.ts  useKeyBind.js
```

Would you update this release to fix this? Thanks.

**Comment by mimshins** [comment]
Done!
Thanks for reporting. You can now safely upgrade to `1.0.2`.
